services:
  anythingllm:
    hostname: anythingllm
    container_name: anythingllm
    build:
      context: ./docker/dockerfile/anythingllm
      dockerfile: dockerfile
    env_file:
      - ./env/anythingllm-docker.env
    ports:
      - 8081:3001
    volumes:
      - ./docker/volume/anythingllm:/app/server/storage
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true
  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./docker/dockerfile/ollama
      dockerfile: dockerfile
    env_file:
      - ./env/ollama-docker.env
    ports:
      - 11434:11434
    volumes:
      - ./docker/volume/ollama:/root/.ollama
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    runtime: nvidia
  anythingllm_db:
    hostname: anythingllm_db
    container_name: anythingllm_db
    build:
      context: ./docker/dockerfile/anythingllm_db
      dockerfile: dockerfile
    env_file:
      - ./env/anythingllm_db-docker.env
    ports:
      - 5433:5432
    volumes:
      - ./docker/volume/anythingllm_db:/var/lib/postgresql/data
    user: root
    stdin_open: true
    tty: true
  postgre_adminer:
    hostname: postgre_adminer
    container_name: postgre_adminer
    image: adminer:5.2.1
    restart: always
    ports:
      - 3001:8080
    stdin_open: true
    tty: true
